version: '3.7'
services:
  dabl:
    build: .
    user: root
    ports:
      - "8000:5000"
    env_file: .env
    restart: always
    links:
      - mariadb:dbserver
  mariadb:
    image: "jsurf/rpi-mariadb"
    env_file: .env-mariadb