version: '3.8'

services:
  web:
    container_name: web
    build: .
    volumes:
      - ./services/web/:/dabl/app/
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:9.6.24-stretch
    container_name: db
    #  volumes:
    #   - postgres_data:/dabl/db
    env_file:
      - .env-postgres

volumes:
  postgres_data: