"""batch history table creation_2

Revision ID: 03949a380153
Revises: 2ec7e5ce7bc6
Create Date: 2021-11-02 21:30:39.991735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03949a380153'
down_revision = '2ec7e5ce7bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_name', sa.String(length=32), nullable=True))
        batch_op.drop_index('ix_batch_history_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=32), nullable=True))
        batch_op.create_index('ix_batch_history_name', ['name'], unique=False)
        batch_op.drop_column('batch_name')

    # ### end Alembic commands ###
