"""batch history table creation

Revision ID: 2ec7e5ce7bc6
Revises: 8381558836c1
Create Date: 2021-11-02 21:22:35.651785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec7e5ce7bc6'
down_revision = '8381558836c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_history_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_history_name'))

    op.drop_table('batch_history')
    # ### end Alembic commands ###
