"""user model changes

Revision ID: 846302678314
Revises: 8b6b0dfd41ea
Create Date: 2021-11-07 14:37:04.233675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846302678314'
down_revision = '8b6b0dfd41ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
