"""add description to batch

Revision ID: fe83393c0300
Revises: dbe01868ccc2
Create Date: 2022-03-09 22:02:36.140669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe83393c0300'
down_revision = 'dbe01868ccc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))

    with op.batch_alter_table('containertypes', schema=None) as batch_op:
        batch_op.drop_column('is_vessel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('containertypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vessel', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
